export { default as authService } from './authService';
export { default as ticketsService } from './ticketsService';
export { default as techniciansService } from './techniciansService';
export { default as usersService } from './usersService';
export { default as analyticsService } from './analyticsService';
export { default as reportsService } from './reportsService';
export { getAdminDashboard } from './adminService';
export { getHODDashboard } from './hodService';
export { getManagerDashboard } from './managerService';
export { getSectionHeadDashboard } from './sectionHeadService';
export { getTechnicianDashboard } from './technicianService';
export { getUserDashboard } from './userDashboardService';
export * from './catalogueService';
export { default as organizationsService, campusesService, departmentsService, campusDepartmentsService, sectionsService as organizationsSectionsService, facilitiesService as organizationsFacilitiesService } from './organizationsService';
